name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install
      run: |
        brew install fastlane
        
    - name: Run fastlane beta
      env:
        MATCH_REPO: ${{ secrets.MATCH_REPO }}
        MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}
        SIGNING_ID: ${{ secrets.SIGNING_ID }}
      run: fastlane beta --verbose

